# Generated by Django 3.0.8 on 2020-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.CharField(max_length=64)),
                ('bookname', models.CharField(max_length=128)),
                ('authorName', models.CharField(max_length=128)),
                ('brief', models.CharField(max_length=1024)),
                ('bookcover1', models.CharField(max_length=64)),
                ('bookcover2', models.CharField(max_length=64)),
                ('bookcover3', models.CharField(max_length=64)),
            ],
        ),
    ]
