# Generated by Django 3.0.8 on 2020-08-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='booktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktype', to='books.Category'),
        ),
    ]
